on:
  pull_request:
    types: [edited, opened, reopened]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Apply dynamic template changes
    steps:
      - uses: luigibertaco/dynamic-template-action
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
